FROM golang:1.19-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY src/gcl/ ./src/gcl/

RUN go build -o gcl-mock ./src/gcl/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/gcl-mock .

EXPOSE 8081

CMD ["./gcl-mock"]
